reader.add=INSERT INTO readers (last_name, first_name, patronymic, birth_date, passport_series, passport_number, address, phone, photo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
reader.update=UPDATE readers SET last_name = ?, first_name = ?, patronymic = ?, birth_date = ?, passport_series = ?, passport_number = ?, address = ?, phone = ?, photo = ? WHERE ticket_number = ?
reader.findByTicketNumber=SELECT * FROM readers WHERE ticket_number = ?
reader.findAll=SELECT * FROM readers ORDER BY last_name ASC
reader.search=SELECT * FROM readers WHERE (CAST(ticket_number AS TEXT) = ? OR last_name ILIKE ? OR phone ILIKE ?) AND is_active = true
reader.changeStatus=CALL sp_change_reader_status(?)